export const ARTISTALBUMLOAD = "ARTISTALBUMLOAD";
export const ARTISTALBUMSUCCESS = "ARTISTALBUMSUCCESS";
export const ARTISTALBUMERROR = "ARTISTALBUMERROR";
export const ARTISTALBUMDELETE = "ARTISTALBUMDELETE";
export const GETARTISTALBUMDATA = "GETARTISTALBUMDATA";